# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Page-alert"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  icon: 
  message:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  icon: ca-gov-icon-bell
  message: 'Notice: DCC is soliciting proposals for the Local Jurisdiction Assistance Grant Program. <a href="#">Learn more</a>.'

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
