# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Step-list"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  steps: [bookshop:step-list-step]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  steps: 
    - bookshop:step-list-step
    - bookshop:step-list-step
    - bookshop:step-list-step

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
