# Metadata about this component, to be used in the CMS
spec:
  structures:
    - regulatory-list
  label: "Regulatory-list-item"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: "A law enforcement agency may only use a person under 21 years of
    age to attempt to purchase alcoholic beverages for delivery to apprehend
    licensees, ..."

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
