# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Link-grid-link"
  description: Individual link block to be used within parent component link-grid
  icon: attachment
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text:
  url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: Link 1 
  url: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
