# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Link-grid"
  description: Grid of links
  icon: grid_view
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  links: [bookshop:link-grid-link]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  links: 
    - bookshop:link-grid-link
    - bookshop:link-grid-link
    - bookshop:link-grid-link

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
