name: Deploy DEV digital.ca.gov
# site:  development.digital.ca.gov
on:
  push:
    branches:
      - development

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3.0.0
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Build Site
        run: |
          npm install
          npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to S3
        run: aws s3 sync --follow-symlinks --delete ./_site s3://development.digital.ca.gov

      - name: Reset cache-control on static fonts
        run: aws s3 sync --cache-control max-age=15552000 ./_site/fonts s3://development.digital.ca.gov/fonts

      - name: Reset cache-control on static img
        run: aws s3 sync --cache-control max-age=15552000 ./_site/img s3://development.digital.ca.gov/img

      - name: invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id E275WGCQ1RLRUJ --paths "/*"